/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ModelConfig {
  /**
   * Out path of generated files.
   */
  out?: string;
  /**
   * Glob used to find models.
   */
  modelGlob: string;
  /**
   * Glob used to ignore models.
   */
  modelIgnoreGlob?: string;
  /**
   * Whether to generate missing models. For example TypeScript to JsonSchema or vice versa.
   */
  generateModel?: boolean;
  /**
   * Generator package used to create components.
   */
  package: string;
  [k: string]: unknown;
}
