/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ShowcaseOptions {
  /**
   * Glob used to find features.
   */
  featureGlob: string;
  /**
   * Glob used to ignore features.
   */
  featureIgnoreGlob?: string;
  /**
   * Whether to init the workspace to run showcase components.
   */
  init?: boolean;
  /**
   * Repository url to link to sources.
   */
  repositoryUrl: string;
  /**
   * Where to write components.
   */
  componentOut: string;
  /**
   * Name of the editor component
   */
  editorName?: string;
  /**
   * Name of readme component
   */
  readmeName?: string;
  [k: string]: unknown;
}
